# Generated by Django 4.2.23 on 2025-07-31 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.IntegerField(choices=[(1, '激しく不満'), (2, 'かなり不満'), (3, 'やや不満'), (4, 'どちらでもない'), (5, 'やや満足'), (6, 'かなり満足'), (7, '激しく満足')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('memo', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
