# Generated by Django 4.2.23 on 2025-08-01 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='satisfaction_level',
            field=models.IntegerField(choices=[(0, '最悪'), (1, '悪い'), (2, '普通'), (3, '良い'), (4, '最高')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
