[phases.setup]
nixPkgs = ['python39', 'postgresql_16', 'gcc']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    '. /opt/venv/bin/activate && python manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn satisfaction_backend.wsgi --log-file -'
